In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns

In [4]:
df=sns.load_dataset('iris')

In [5]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [14]:
model=sm.Logit(np.array(y_train),sm.add_constant(np.array(x_train)))

TypeError: '>=' not supported between instances of 'str' and 'int'

In [15]:
from sklearn.datasets import make_classification

In [26]:
x,y=make_classification(n_samples=100,
    n_features=20,
    n_informative=20,
    n_redundant=0,
    n_repeated=0,
    n_classes=4,
    n_clusters_per_class=2,
    weights=None,
    flip_y=0.01,
    class_sep=1.0,
    hypercube=True,
    shift=0.0,
)

In [27]:
x

array([[ 4.4710482 , -0.12645954,  1.30247818, ..., -2.37159343,
        -2.47294554, -1.40306969],
       [-3.08379434, -1.19402401,  5.10678772, ..., -0.31835119,
         3.91050041,  2.42707227],
       [-1.43159863,  4.77582973, -2.51509096, ...,  0.28438896,
         0.86721711, -1.45533317],
       ...,
       [-2.60010179,  1.76684445, -3.97834939, ...,  1.09548439,
         1.2399966 , -4.00919889],
       [ 0.17100438,  3.0753271 ,  2.39575947, ..., -5.37057302,
        -3.02141917, -2.22539949],
       [-0.64547231,  2.97026468, -3.13199452, ..., -2.98457794,
         5.8025951 , -0.63954647]])

In [28]:
y

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

In [29]:
logi=sm.Logit(y,sm.add_constant(x))

In [30]:
logi.fit().summary()

Optimization terminated successfully.
         Current function value: 0.171864
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  100
Model:                          Logit   Df Residuals:                       79
Method:                           MLE   Df Model:                           20
Date:                Wed, 06 Nov 2019   Pseudo R-squ.:                  0.7521
Time:                        21:27:17   Log-Likelihood:                -17.186
converged:                       True   LL-Null:                       -69.315
                                        LLR p-value:                 2.164e-13
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1019      0.820     -0.124      0.901      -1.710       1.506
x1            -1.4914      0.505     -2.951      0.003      -2.482      -0.501
x2            -0.4563      0.303     -1.504      0.133      -1.051       0.138
x3            -0.1177      0.264     -0.446      0.656      -0.635       0.399
x4            -0.1231      0.264     -0.466      0.641      -0.641       0.395
x5             0.8330      0.353      2.363      0.018       0.142       1.524
x6             0.4553      0.318      1.433      0.152      -0.167       1.078
x7            -0.6359      0.363     -1.751      0.080      -1.348       0.076
x8            -0.1379      0.236     -0.585      0.558      -0.600       0.324
x9            -0.3268      0.286     -1.144      0.253      -0.887       0.233
x10           -1.4223      0.513     -2.772      0.006      -2.428      -0.417
x11           -0.6526      0.357     -1.826      0.068      -1.353       0.048
x12           -0.2304      0.269     -0.858      0.391      -0.757       0.296
x13            0.1561      0.290      0.538      0.591      -0.413       0.725
x14            1.2525      0.473      2.651      0.008       0.326       2.179
x15            0.8200      0.393      2.084      0.037       0.049       1.591
x16            0.2345      0.265      0.884      0.376      -0.285       0.754
x17           -0.1861      0.308     -0.605      0.545      -0.789       0.417
x18           -0.7726      0.350     -2.209      0.027      -1.458      -0.087
x19           -0.1566      0.254     -0.618      0.537      -0.654       0.340
x20            1.2031      0.456      2.636      0.008       0.309       2.098
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

from logit results you can observe 2 tables.1)the first one is about the dataset and the model performances
2)2nd one is about the weights of the model

<u>converged</u> this tells wheather the classification model has reached convergence while being trained.use the model only if this parameter is true.

<u>log-likelihood:</u>this the logarithem of the likelihood.it maximizes the our required function.

<u>LLnull</u>:this is log likelihood when only intercept used as a predictor

<u>LLR P-VALUE</u>: this is the chisquared probability of getting log likelihood ratio statically greater than llr.basically it shows how the model is better than guessing with a constant value.

<u>LLR</u>that is the logarithem of the likelihood of the null model divided by the likelihood of the alternate model(with out null)

<u>PSEUDO R SQUARED: this can be seen as the proportion of the total variability un explained by the model.it's computed as <u>[1-loglikelihood/LL-NULL]</u>

Z:this is the ratio between the standard error and the coeffiient(it is the statical t value

p>|z| this is the probability of obtaining a t value greater than z,while sampling taking from the same population.

In [31]:
x,y=make_classification(n_samples=100,
    n_features=20,
    n_informative=20,
    n_redundant=0,
    n_repeated=0,
    n_classes=4,
    n_clusters_per_class=2,
    weights=None,
    flip_y=0.01,
    class_sep=1.0,
    hypercube=True,
    shift=0.0,
)

In [32]:
x

array([[ 5.35287132e-03,  5.56928261e+00, -5.27386572e+00, ...,
         1.44371208e-01,  3.44082077e-01,  2.61436406e+00],
       [-1.68377747e+00, -2.13050003e+00,  1.57393849e+00, ...,
         1.27447666e+00,  1.10901150e+00, -1.78217688e+00],
       [ 3.59880730e-01,  4.48354669e-01,  1.86860863e+00, ...,
         3.70543642e+00, -3.82142956e+00, -3.64523940e+00],
       ...,
       [-4.10522469e-01,  1.81734431e+00, -5.35148698e-01, ...,
         1.02475772e+00, -1.53773098e-01,  2.70040540e-01],
       [ 2.11822399e+00,  4.21252542e+00,  1.95272782e-01, ...,
         4.65562343e+00,  2.39103022e+00,  3.99196350e+00],
       [-3.85096336e+00,  2.17905018e-01,  1.95554082e+00, ...,
         6.22276057e-01, -2.06627072e+00, -3.90721895e+00]])

In [33]:
y

array([1, 0, 1, 3, 3, 2, 0, 1, 0, 2, 1, 2, 0, 1, 0, 3, 2, 3, 3, 3, 1, 3,
       2, 3, 1, 3, 1, 2, 2, 2, 2, 0, 0, 3, 1, 1, 3, 2, 3, 2, 2, 0, 3, 1,
       1, 0, 3, 2, 0, 0, 0, 2, 0, 1, 0, 2, 3, 2, 1, 0, 2, 0, 1, 2, 0, 0,
       3, 1, 2, 3, 3, 0, 3, 2, 2, 0, 3, 1, 0, 3, 1, 1, 3, 2, 1, 1, 1, 1,
       2, 0, 0, 2, 0, 3, 3, 0, 3, 1, 2, 1])

In [34]:
logi=sm.Logit(y,sm.add_constant(x))

ValueError: endog must be in the unit interval.